default:
  adapter: postgresql
  database: food_rescue_development
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: food_rescue_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: food_rescue_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: food_rescue_production
  pool: 5
  timeout: 5000
